name: This Day Burns
favicon: null
layout_spectrum: 0.6966964409220964
typography_spectrum: 0.6920034370850772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.13478840282186866
  lightness: 0.044039810076355934
  saturation: 0.7232214699033648
  rhythmicContrast: 0.42640850506722927
purpose: []
