name: This Day Burns
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1865
title: This Day Burns
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
